# (PART\*) Lab 11 {-}

# Fictional Animal Systems Presentation {-}

*Last updated `r Sys.Date()`*

### Overview of the Week {-}

Your TA will pre-determine the order of your presentations and will let you know ahead of time.  Please ensure you are ready to go.  As this is the last lab and it requires a presentation during your scheduled lab section there will not be the option to submit 24 hours late.

# Presentation Rubric {-}

**Total /38**

### System Integration {-}

This criterion is linked to a Learning Outcome **System Integration**. All systems and regulatory strategies have been thoroughly explained

**Possible Points 8**

| Ratings | Comment |
| --- | --- |
| 8 pts | Excellent. All four systems are represented and explained. |
| 6 pts | Proficient. 3 of the 4 systems are represented and explained. |
| 4 pts | Satisfactory. 1-2 of the systems are represented and explained. |
| 2 pts | Unsatisfactory. It is unclear what system is being included. |

This criterion is linked to a Learning Outcome **System Integration**. All systems and regulatory strategies have been thoroughly explained. This criterion is linked to a Learning Outcome System integration Systems are compatible with each other as described in the final version of the animal.

**Possible Points 10**

| Ratings | Comment |
| --- | --- |
| 10 pts | Excellent. The compatibility of all 4 systems has been reasoned logically and fully explained for all 4 systems. |
| 8 pts | Proficient. The compatibility of the 3 systems has been reasoned logically and explained. |
| 6 pts | Satisfactory. The compatibility of the 2 systems has been reasoned logically and explained systems. |
| 4 pts | Developing. The compatibility of only 1 system has been reasoned logically and explained systems. | 
| 2 pts | Unsatisfactory. Compatibility between the systems is not clearly described. |

### Life Cycle {-}

This criterion is linked to a Learning Outcome **Life Cycle**. The full life cycle has been provided and all structures and ploidy are indicated.

**Possible Points 4**

| Ratings | Comment |
| --- | --- |
| 4 pts | Excellent. All criteria are met. |
| 3 pts | Proficient. 3/4 of the criteria are met. |
| 2 pts | Satisfactory. Half of the criteria are met. |
| 1 pts | Developing. The life cycle has been provided but does not fulfill the remaining requirements. | 
| 0 pts | Unsatisfactory. No life cycle was provided. |

### Environment {-}

This criterion is linked to a Learning Outcome **Environment**. Explained how animal and their systems are compatible with the environment.

**Possible Points 2**

| Ratings | Comment |
| --- | --- |
| 2 pts | Excellent. Logical. |
| 1 pts | Satisfactory. Illogical or incomplete. |
| 0 pts | Unsatisfactory. One member of the group is primarily presenting and expertise is not demonstrated. |

This criterion is linked to a Learning Outcome **Environment**. Description of how animal functions/lives/is affected by its environment.

**Possible Points 2**

| Ratings | Comment |
| --- | --- |
| 2 pts | Excellent. Present and consistent between the animal and its environment. |
| 1 pts | Satisfactory. Present but inconsistent between the animal and its environment. |
| 0 pts | Unsatisfactory. Absent. |

### Overall {-}

This criterion is linked to a Learning Outcome **Overall description**. Backbone, body design, appendages, covering, size, etc. selections.

**Possible Points 3**

| Ratings | Comment |
| --- | --- |
| 3 pts | Excellent. All consistent within the animal and it's physiological systems. |
| 2 pts | Proficient. Some inconsistencies within the animal or with its systems. |
| 1 pts | Satisfactory. Most or all inconsistent within the animal and/or its systems. |
| 0 pts | Unsatisfactory. Drawing and description are unclear and non-informative. |

This criterion is linked to a Learning Outcome **Overall**. The presentation style is clear, had sensible flow, volume was appropriate, and the presenter was engaging

**Possible Points 3**

| Ratings | Comment |
| --- | --- |
| 3 pts | Excellent. All criteria are met. |
| 2 pts | Proficient. 3 of the four criteria have been met. |
| 1 pts | Developing. 1-2 of the criteria have been met. |
| 0 pts | Unsatisfactory. 0-1 of the criteria have been met. |

### Scientific Information {-}

This criterion is linked to a Learning Outcome **Scientific Information**. Details of the process of each system were conveyed with appropriate terminology.

**Possible Points 3**

| Ratings | Comment |
| --- | --- |
| 3 pts | Excellent. All of the structures and associated functions for each system were described. |
| 2 pts | Proficient. Most of the structures and their associated functions for each system were described. |
| 1 pts | Developing. Some of the structures and their associated functions for each system were described. |
| 0 pts | Unsatisfactory. Many of either the structure or their associated functions were missing. |

### Presentation {-}

This criterion is linked to a Learning Outcome **Presentation**. Evidence that the student can communicate their ideas accurately and in a meaningful way.

**Possible Points 3**

| Ratings | Comment |
| --- | --- |
| 3 pts | Excellent. Every major point is well supported and well-articulated. The presenter engages with the audience while conveying a clear understanding of knowledge and understanding of their systems. |
| 2 pts | Proficient. Every major point is adequately supported and well-articulated. The presenter engages with the audience while conveying an adequate understanding of knowledge and understanding of their systems. |
| 1 pts | Developing. Many of the points are adequately supported and articulated. The presenter engages with the audience to some degree but does read from their notes and only partially convey's the necessary information. |
| 0 pts | Unsatisfactory. The presenter is reading word for word notes and does not seem to be able to articulate information about their animal systems. |